Reset application.db and  wasm
CosmosContracts/juno pull request #312
Opened 2022-10-08 18:21 UTC by chillyvee

Is there a better way to reset application.db and wasm?  For example by extending into the "tendermint" reset-state command?

2022-10-16 15:00 UTC, the-frey commented
This looks potentially useful.

Would also say that it's worth maybe removing cache as well in a separate command 🤔 

There have been a bunch of changes on main though so might be easier to start fresh and just add these changes (or rebase)

2022-10-20 18:35 UTC, chillyvee commented
Can take another look soon since testnet completed the upgrade.

2022-10-25 17:49 UTC, chillyvee commented
> Would also say that it's worth maybe removing cache as well in a separate command 🤔

Split the `application.db` and `wasm` reset commands

Rebased on main

2022-11-01 09:08 UTC, vuong177 commented on cmd/junod/tendermint.go
> +			fmt.Println("error removing wasm", "dir", wasmDir, "err", err)
return fmt.Errorf("error removing wasm %s dir: err %w", wasmDir, err)

2022-11-01 09:10 UTC, vuong177 commented on cmd/junod/tendermint.go
> +			fmt.Println("error removing application.db", "dir", appDir, "err", err)
```suggestion
			return fmt.Errorf("error removing application.db  dir: %s; err: %w", wasmDir, err)

2022-11-01 09:11 UTC, vuong177 commented on cmd/junod/tendermint.go
> +			fmt.Println("error removing wasm", "dir", wasmDir, "err", err)
```suggestion
			return fmt.Errorf("error removing wasm  dir: %s; err: %w", wasmDir, err)
```

2022-11-01 09:13 UTC, vuong177 requested changes

2022-11-01 09:13 UTC, vuong177 commented on cmd/junod/tendermint.go
> +		fmt.Println("unable to recreate application.db", "err", err)
same nits
```suggestion
		return fmt.Errorf("unable to recreate application.db %w", err)
```

2022-11-01 09:13 UTC, vuong177 commented on cmd/junod/tendermint.go
> +		fmt.Println("unable to recreate wasm", "err", err)
same nits
```suggestion
		return fmt.Errorf("unable to recreate wasm %w", err)
```

2022-11-01 09:29 UTC, vuong177 commented
@chillyvee, thanks for making this. Only some minors left, I will approve when it is addressed.

2022-11-01 12:46 UTC, chillyvee commented
@vuong177 Thank you for the feedback.  We'll get this amended as soon as we have a chance.

2022-11-01 12:56 UTC, chillyvee commented
@vuong177 Your suggestions have been added to the branch

2022-11-14 19:43 UTC, Reecepbcups approved these changes
Approved but my only thought is should we have this in the root commands?
or make its own reset section? `junod reset app`, `junod reset wasm` @chillyvee 

In the future we may want to add resetting config files like app.toml as well to default

2022-11-18 06:29 UTC, merged