Bumps juno version to v12
CosmosContracts/juno pull request #349
Opened 2022-11-02 04:34 UTC by vuong177

- Bumps version to v12

2022-11-07 22:14 UTC, faddat approved these changes

2022-11-08 19:37 UTC, faddat approved these changes

2022-11-08 19:44 UTC, faddat requested changes
I believe I broke it...

2022-11-09 10:26 UTC, the-frey commented
Looks good, should we get this in before other PRs so they have to rebase on top, since it's minor?

2022-11-09 14:46 UTC, faddat submitted a review, later dismissed

2022-11-09 15:24 UTC, faddat approved these changes

2022-11-10 06:58 UTC, faddat approved these changes

2022-11-12 08:34 UTC, catShaark approved these changes

2022-11-12 08:36 UTC, merged