packet forward middleware
CosmosContracts/juno pull request #432
Opened 2022-12-18 19:22 UTC by faddat

2022-12-24 07:13 UTC, faddat commented
This merges the [faddat/make-proto-only](https://github.com/CosmosContracts/juno/tree/faddat/make-proto-only) branch in here, to ensure that it was the needed fix.

2022-12-24 07:19 UTC, faddat commented
@vuong177 @Reecepbcups @GNaD13 - guys, getting some pretty serious proto cross-talk here. 

Also over here:

https://github.com/CosmosContracts/token-factory/pull/1

2022-12-25 18:14 UTC, faddat commented
@Reecepbcups fyi I think that the proto changes you made to feeshare resolved the issues here.

2022-12-26 05:34 UTC, faddat commented
To guide review:

https://github.com/CosmosContracts/juno/actions/runs/3779340500/jobs/6424514084#step:9:13

2022-12-28 21:27 UTC, Reecepbcups requested changes
Also should add an e2e test for this to ensure it works correctly

2022-12-28 21:27 UTC, Reecepbcups commented on app/keepers/keepers.go
> +	appKeepers.RouterKeeper = routerkeeper.NewKeeper(
new keeper, so the key should be added to the v12 upgrade handler store & any params required

2023-01-01 18:46 UTC, faddat commented
@Reecepbcups I agree about e2e

I also think that this is a reasonable place to segue into possibly using IBC test, maybe after we do the UNI deployment.

But I still do need to figure out how to use it to simulate the test against the live state.

2023-01-03 22:11 UTC, Reecepbcups commented
Push the v13 if we can't figure out where test are, which just leaves oracle left for review

2023-01-05 09:13 UTC, faddat commented
Yeah I think that makes perfect sense

2023-01-09 18:08 UTC, Reecepbcups commented
**Monday Meeting** Pushed to v13 officially

2023-01-12 18:41 UTC, faddat commented
Did a merge here for some testing for:

https://github.com/strangelove-ventures/packet-forward-middleware/pull/45

2023-01-16 01:41 UTC, Reecepbcups commented
Closing in favor of Andrews more simple PR without go.mod replace (since its merged in now to mainline)
Will add E2E test after that

2023-01-16 01:41 UTC, closed without merging