Oracle tests: multiple denom, denom with no entries; endBlocker tests
CosmosContracts/juno pull request #463
Opened 2022-12-29 11:47 UTC by udit-gulati

1. Adds price history test for when we have multiple denominations (one denom is prefix of another also covered), to make sure that multiple denom entries does not interfere with each other.
2. Adds price history test for when price is queried for denom which hasn't been stored yet.
3. Adds abci tests for EndBlocker to see if price is correctly stored after validator vote period is over.

To discuss:
1. `getHistoryEntryBetweenTime()` returns `[]types.PriceHistoryEntry(nil)` instead of `[]types.PriceHistoryEntry{}` when the denom does not have stored prices. Is it expected or should be changed?
2. `GetArithmetricTWAP()` throws errror `no values in range` when there is no price entry for given denom before `startTime` becuase the first and last price entry is fetched using `getHistoryEntryAtOrBeforeTime()` and it throws error for `startTime`. IMO this should be handled in `GetArithmetricTWAP()` and values must be returned even if there is no price entry before `startTime`.
3. I've left TODO in comments for both of the above.

2022-12-30 01:32 UTC, vuong177 commented on x/oracle/keeper/history_test.go
> +func TestStoreAndGetMultipleHistoricalData(t *testing.T) {
This test should be split into smaller tests, it's too long and hard to track.

2022-12-30 01:36 UTC, vuong177 commented
@udit-gulati thanks for this PR. I think we should use driven-table test cases for this, it's easier for tracking and debugging.

2022-12-30 01:45 UTC, vuong177 requested changes
`TestStoreAndGetMultipleHistoricalData` should be split into smaller tests, it's too long and hard to track.

2022-12-30 01:58 UTC, vuong177 commented on x/oracle/keeper/history_test.go
> +func TestStoreAndGetMultipleHistoricalData(t *testing.T) {
it should be split into smaller tests.

2022-12-30 01:58 UTC, vuong177 commented on x/oracle/keeper/history_test.go
> +	timeNow := time.Now().UTC()
Using a driven table test for this case could make more clear && easier to debug!

2022-12-30 02:30 UTC, vuong177 commented
> 1. getHistoryEntryBetweenTime() returns []types.PriceHistoryEntry(nil) instead of []types.PriceHistoryEntry{} when the denom does not have stored prices. Is it expected or should be changed?

it's nil slice and empty slice, those thing is different but their observable behavior is the same.

2023-01-01 18:53 UTC, faddat commented
Very nice. Thank you for your work Udit.

@vuong177 Does this conflict with the table driven testing PR that I just merged?

If it adds additional test coverage, I'm likely in support of it. Thanks for your review.

2023-01-02 09:14 UTC, faddat commented
@vuong177 -- checking through this, my feeling is that we should merge, then triage in an additional issue.  I'm happy to have the coverage.

2023-01-02 09:14 UTC, merged