[v12 - DNM yet] Cleanup of v12 codebase
CosmosContracts/juno pull request #509
Opened 2023-01-13 14:35 UTC by Reecepbcups

cleanup of any thing we find when reviewing over the v12 update

- removes screen from oracle docs

2023-01-13 18:37 UTC, faddat commented
Personally, I'd keep screen.

It isn't the best way to run the oracle, but the difference is that it allows operators to see what is going on.

2023-01-14 20:23 UTC, Reecepbcups commented
Is `add-ica-config` required to sync from older versions @the-frey or just local testing?

If so I will make c3c1a80d9237c84020ae6e584b3f375363dd565c the new `add-ica-config`, and move previous messages to `v11-add-ica-config`. Just wanted to double check

2023-01-16 08:39 UTC, the-frey commented
the add ica config command is to help generating genesis files that match mainnet config. So yeah, docker, testing, localnets, stuff like that. So what you've done is right, we'd want v12 to have it, or main just after v12. What you've done makes sense tho

2023-01-16 16:16 UTC, Reecepbcups commented
@udit-gulati So the CI was not correctly running for the oracle on main, which is why your other pr #514 passed. 

The test actually fails for grpc query "Error - Start time before first entry" as you can see above. 
Can you target a PR to this branch & resolve that? Thanks

2023-01-16 16:57 UTC, udit-gulati commented
@Reecepbcups it now calculates TWAP when start time is before first entry, I've updated the test https://github.com/CosmosContracts/juno/pull/517. Let me know if this shouldn't be the expected behaviour.

2023-01-16 17:36 UTC, jackzampolin commented
plz no screen

2023-01-17 14:34 UTC, the-frey commented
LGTM

2023-01-17 15:57 UTC, faddat approved these changes
Approved with the note that force prune will probably break in the next version.

2023-01-17 16:47 UTC, faddat commented
Oh, you fixed the thing I was fixing.  Strong approve.

2023-01-17 16:49 UTC, faddat commented
--- FAIL: TestOracleTestSuite (0.04s)
    --- FAIL: TestOracleTestSuite/TestEndblockerHistoracle (0.04s)
        abci_test.go:155: 
            	Error Trace:	/home/runner/work/juno/juno/x/oracle/abci_test.go:155
            	Error:      	Should be true
            	Test:       	TestOracleTestSuite/TestEndblockerHistoracle
FAIL


I... need to fix spelling sir.  

ALso need to know if that is HistOracle

or Historical

2023-01-17 16:49 UTC, faddat requested changes
brb

2023-01-17 16:51 UTC, Reecepbcups commented
> --- FAIL: TestOracleTestSuite (0.04s) --- FAIL: TestOracleTestSuite/TestEndblockerHistoracle (0.04s) abci_test.go:155: Error Trace: /home/runner/work/juno/juno/x/oracle/abci_test.go:155 Error: Should be true Test: TestOracleTestSuite/TestEndblockerHistoracle FAIL
> 
> I... need to fix spelling sir.
> 
> ALso need to know if that is HistOracle
> 
> or Historical

This randomly fails sometimes, then passes others. Its like e2e. IDK why oracle is so weird like this

2023-01-17 16:55 UTC, faddat commented
Interesting about the failure -- my changes really just aim at readability

Historacle

sounds too. much like "historical"

2023-01-17 16:56 UTC, faddat approved these changes

2023-01-17 16:56 UTC, faddat commented
...he says, while he makes a spelling error in a commit message...

2023-01-17 20:26 UTC, JakeHartnell commented on cmd/junod/cmd/balances_from_state_export.go
> +// StakedToCSVCmd generates a airdrop.csv from a provided exported balances.json.
OMG, this is soooooo nice.

2023-01-17 20:28 UTC, JakeHartnell commented on cmd/junod/cmd/forceprune.go
> +// forceprune gets cmd to convert any bech32 address to an osmo prefix.
```suggestion
```

Comment is wrong. It does not do this. :joy:

2023-01-17 20:30 UTC, JakeHartnell approved these changes
BEAUTIFUL. :shipit:

2023-01-17 20:32 UTC, merged