Integrate packet forward middleware
CosmosContracts/juno pull request #513
Opened 2023-01-16 00:11 UTC by agouin

Integrates v4 of https://github.com/strangelove-ventures/packet-forward-middleware into the transfer middleware stack to enable atomic multi-hop through Juno.

callback flow: `hooks -> ics29 fee -> packet forward -> transfer module`
send packet direction: `transfer module -> packet forward -> hooks -> channel`

ibctest e2e test [here](https://github.com/strangelove-ventures/ibctest/blob/andrew/juno_v12_pfm_test/examples/ibc/packet_forward_test.go)

2023-01-16 01:40 UTC, Reecepbcups requested changes
LGTM other than needs upgrade set in app/upgrades/v12

`constants.go -> storeKey routertypes.ModuleName`
and
`upgrades.go -> keepers.RouterKeeper.SetParams(ctx, routertypes.DefaultParams())`

Then I will work on the e2e test after merge thanks Andrew

2023-01-16 21:18 UTC, agouin commented
> Upgrade from v11 -> v12 worked for me after that

Thank you, I applied those changes.

> junod tx ibc-transfer transfer transfer channel-0 "juno1hj5fveer5cjtn4wd6wstzugjfdxzl0xps73ftl|transfer/channel-1:juno10c3slrqx3369mfsr9670au22zvq082jaej8ve4" 111ujuno $CHAIN_A_ARGS --packet-timeout-height 0-0

The packet forward middleware no longer uses an overloaded receiver. The migration is documented in [this PR](https://github.com/strangelove-ventures/packet-forward-middleware/pull/36)

We don't have example bash scripts, but you can run the [packet forward middleware e2e test in ibctest](https://github.com/strangelove-ventures/ibctest/blob/andrew/juno_v12_pfm_test/examples/ibc/packet_forward_test.go) and swap out for a local/remote juno image.

2023-01-16 21:31 UTC, Reecepbcups approved these changes

2023-01-17 15:48 UTC, faddat commented
As implemented doesn't this break IBC hooks?

2023-01-17 15:52 UTC, faddat commented on app/keepers/keepers.go
> -		appKeepers.HooksICS4Wrapper,
Later on, I see IBC hooks but We use a pointer

2023-01-17 15:53 UTC, faddat commented on app/keepers/keepers.go
> +		&appKeepers.HooksICS4Wrapper,
This has changed, why is that?

Note: it could all be perfectly fine but definitely want to check

2023-01-17 15:53 UTC, faddat requested changes
I will resolve this change request  if I can figure out what the changes are doing here

2023-01-17 16:04 UTC, Reecepbcups commented
> As implemented doesn't this break IBC hooks?

@faddat - It does not break IBC-Hooks, seems to work just fine:
![image](https://user-images.githubusercontent.com/31943163/212949620-30c97d7b-b6fe-46fb-ad05-0184b8abdc79.png)

2023-01-17 16:29 UTC, faddat commented
ok.  I was about to do the check you've now done.  lgtm

2023-01-17 16:30 UTC, faddat approved these changes

2023-01-17 16:30 UTC, merged