Set keyring-backend in setup script
CosmosContracts/juno pull request #79
Opened 2021-11-01 04:52 UTC by giansalex

2021-11-02 17:41 UTC, joeabbey requested changes
a few recommendations:
avoid splitting by surrounding with quotes
allow the default `test` to be overridden 
explicitly specify --keyring-backend and then use the variable the select the backend.

2021-11-02 17:41 UTC, joeabbey commented on docker/setup_junod.sh
> +KEYRING="--keyring-backend test"
```suggestion
KEYRING="${KEYRING:-test}"
```

2021-11-02 17:41 UTC, joeabbey commented on docker/setup_junod.sh
> +  (echo "$PASSWORD"; echo "$PASSWORD") | junod keys add validator $KEYRING
```suggestion
if ! junod keys show validator --keyring-backend "$KEYRING"; then
  (echo "$PASSWORD"; echo "$PASSWORD") | junod keys add validator  --keyring-backend "$KEYRING"
```

2021-11-02 17:41 UTC, joeabbey commented on docker/setup_junod.sh
> +echo "$PASSWORD" | junod add-genesis-account validator "1000000000$STAKE,1000000000$FEE" $KEYRING
```suggestion
echo "$PASSWORD" | junod add-genesis-account validator "1000000000$STAKE,1000000000$FEE" --keyring-backend "$KEYRING"
```

2021-11-02 17:41 UTC, joeabbey commented on docker/setup_junod.sh
> +(echo "$PASSWORD"; echo "$PASSWORD"; echo "$PASSWORD") | junod gentx validator "250000000$STAKE" --chain-id="$CHAIN_ID" --amount="250000000$STAKE" $KEYRING
```suggestion
(echo "$PASSWORD"; echo "$PASSWORD"; echo "$PASSWORD") | junod gentx validator "250000000$STAKE" --chain-id="$CHAIN_ID" --amount="250000000$STAKE"  --keyring-backend "$KEYRING"
```

2021-11-02 18:23 UTC, joeabbey commented
> @joeabbey this script is for testing purpose.

Ah cool, consider my comments all resolved :)

2021-11-02 18:23 UTC, joeabbey approved these changes

2021-11-09 15:17 UTC, faddat approved these changes
I like the whole thing.  It is a great idea to have a script like this one.

2021-11-12 18:11 UTC, giansalex commented on docker/setup_junod.sh
>  sed -i 's/"time_iota_ms": "1000"/"time_iota_ms": "10"/' "$HOME"/.juno/config/genesis.json
`time_iota_ms` will be removed https://github.com/tendermint/tendermint/pull/5987

2021-11-16 17:24 UTC, JakeHartnell approved these changes

2021-11-17 13:26 UTC, merged