chore!: v22 Namespace & Upgrade Handler
CosmosContracts/juno pull request #993
Opened 2024-04-09 10:35 UTC by dimiandre

1. v22 upgrade handler
2. v22 namespace
3. version bumps - including ibc-go

2024-04-09 11:07 UTC, dimiandre commented
seems tests are broken because of 
https://github.com/strangelove-ventures/interchaintest/pull/1043

thanks @faddat for pointing out

2024-04-09 20:48 UTC, Reecepbcups commented
Comet had a minor state breaking change (types). Can use `github.com/cometbft/cometbft => github.com/cometbft/cometbft v0.37.2` as well since interchaintest does not depend on actual cometbft, but rather just the types and func signatures

2024-04-10 07:49 UTC, dimiandre commented
> Comet had a minor state breaking change (types). Can use `github.com/cometbft/cometbft => github.com/cometbft/cometbft v0.37.2` in the `interchaintest/` go.mod as well since interchaintest does not depend on actual cometbft, but rather just the types and func signatures

thanks reece! seems to do the trick!

2024-04-10 09:26 UTC, dimiandre commented
> Are the version bumps needed for this specific chain upgrade or can we do them later, eg. with the help of a new maintainer from Dev Dept's Blockchain engineer RFP? (ofc help by anyone in the community is always appreciated and could be retroactively compensated).
> 
> I see a lot of errors (in 8 out of 9 x/modules + in app/apptesting/test_suite.go and app/test_helpers.go, etc.) are caused by the missing functions `RequestBeginBlock` & `RequestEndBlock` in the new **cometbft**. We are bumping it from 0.37.2 to 0.38.4, but they were removed starting from `v0.38.0`, and I'm a noob but it doesn't seem required: ![image](https://private-user-images.githubusercontent.com/4728367/321170829-d4a279ce-c2ab-4951-bab6-dbb2ad3267c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDA0NjMsIm5iZiI6MTcxMjc0MDE2MywicGF0aCI6Ii80NzI4MzY3LzMyMTE3MDgyOS1kNGEyNzljZS1jMmFiLTQ5NTEtYmFiNi1kYmIyYWQzMjY3YzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDkwOTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFkZDc2MWEzMjI4YmQ4OWNmZjBkZmVlMWQwMjg0OGVmZjkxYzUyZjc3YTM1ZTExZGZiZDYyYjg0OThmOGQ4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dDxOmXmkfZAb_hglZhF9EKxMN-6BEuahWpJoWvBkyA4)
> 
> EDIT: I had this comment ready but I posted it late 😅 Happy that you already figured the issue out and that I'm learning to review PRs here 😇

version bumps here are minor, and needed to solve the security issues we had with ibc-go. 
When you tidy go deps the versions get minor-bumped automatically

Also ibc-go v7.4 is state breaking comparing v7.3 that's why i'm cutting the v22 release

2024-04-10 09:29 UTC, dimiandre commented on docker-compose.yml
No, that is used only for local tests. 

Nothing to do with production builds

2024-04-10 09:29 UTC, kopeboy commented on docker-compose.yml
> +      - UNSAFE_CORS=true
I guess we'll need to remember to disable UNSAFE_CORS before merging into a release, right?

2024-04-10 09:30 UTC, kopeboy commented on interchaintest/go.mod
> +	github.com/cometbft/cometbft => github.com/cometbft/cometbft v0.37.2
Shouldn't this be `v0.37.4`?

2024-04-10 09:35 UTC, kopeboy approved these changes

2024-04-11 05:18 UTC, faddat commented
Every time Juno is upgraded, best practices are:

* use the latest major golang release
* use the latest release of EVERY cosmos ecosystem package

The reason for this is that there are frequently security improvements, and performance improvements.  I can't think of a time when it was a bad thing to use the latest dependencies.  It is reasonable to use cosmos-sdk and ibc-go as a guide for what's freshest.

2024-04-11 05:26 UTC, faddat requested changes
This doesn't update some ecosystem libraries.  I've done the updates, you'd just need to merge the PR below:

https://github.com/CosmosContracts/juno/pull/994

2024-04-19 00:04 UTC, Reecepbcups commented on x/tokenfactory/keeper/bankactions.go
> +	sort.Strings(sortedPermAddrs)
is this deterministic? I know sort.Slice is not, I assume it's the same here?

If you can't sort, iter through all, don't break early. Then if an error, return after the for loop

2024-04-19 00:04 UTC, Reecepbcups commented on x/tokenfactory/keeper/bankactions.go
> +			return status.Errorf(codes.Internal, "send from module acc not available")
How would someone send from a module account? do you mean toAcc? not following here.

if there is an issue I would like to get it upstreamed to my own widely used fork of TF but I don't see the case here

2024-04-21 14:22 UTC, JakeHartnell approved these changes

2024-04-21 14:26 UTC, merged